name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  test:
    name: Running Units Tests 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      id: test
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: 
        npm install
        npm build
    - uses: LouiseBrunner/checks-action@v0.1.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name:  Test XYZ
        conclusion: ${{ job }}
#    - name: Test
#      run: npm test
